### ISSUE TITLE
Add a healthcheck endpoint

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/safepass#30]
- [x] Create an API endpoint which returns status code `200`
- [x] Choose a short, good message
- [x] Update the SafePass monitors on [Up](https://up.josa.ngo) (ask George or Tamim for help)

## Resources & recommendations

- Since it's a flask API all you need to do is create a get `def` and provide the decorator with the `/healthcheck` route.  
- Checkout a new branch from `development`. Use the `dev-frozen` branch for reference.

Your starting point should be in [main.py](https://github.com/jordanopensource/safepass/blob/development/snappass/main.py)

**Comment by mbaraa** [comment]
@thamudi the Kuma update will be done after deploying the merged branch!

**Comment by thamudi** [comment]
Needs some configueration to serve JSON files from NGINX
