### ISSUE TITLE
Setup Matomo

### ISSUE THREAD

**Issue by thamudi** [jordanopensource/safepass#31]
# Use case

As an Admin at JOSA I want to use Matomo so I would know how many visits I got into my site ([safepass.josa.ngo](https://safepass.josa.ngo))

## Recourse & recommendations

You will need to use the Matomo Site ID and URL in order to set it up.

MATOMO_URL: `https://analytics.josa.ngo`
MATOMO_ID: `14`

You can find code that was done on [dev-frozen main.py](https://github.com/jordanopensource/safepass/blob/79c82116121f0e6fb5a3007eae74aef601b0ed5c/snappass/main.py#L19) but needs testing.

## Checklist 

- [x] implement matomo url and id as env variables.
- [x] inject the ID into the template.
- [x] Check if analytics are getting info on the site. (Check with George or Tamim for help)

**Comment by thamudi** [comment]
@mbaraa Can you please try again while disabling the DNT?

**Comment by mbaraa** [comment]
I did, it was still not working, I think it's a whitelist thingy from Matomo itself.
